# Default Spring Profile
server:
  error:
    include-message: always
frontend:
  url: http://localhost:3000/

backend:
  url: http://localhost:8080/

website:
  domain: localhost

logging:
  level:
    root: INFO
    com.example: DEBUG # package name
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

---
# for H2 tests
spring:
  config:
    activate:
      on-profile: h2

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:movingsystem-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        auto-quote-keyword: true

  sql:
    init:
      platform: h2
      mode: always

frontend:
  url: http://localhost:3000/

backend:
  url: http://localhost:8080/

website:
  domain: localhost

logging:
  level:
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: DEBUG

---
#for docker

spring:
  config:
    activate:
      on-profile: docker
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:mysql://db-movingexpress-do-user-15580099-0.c.db.ondigitalocean.com:25060/movingexpress-db
    username: ${spring.mysql.username}
    password: ${spring.mysql.password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  error:
    whitelabel:
      enabled: false
    include-binding-errors: always
    include-message: always
  port: 8080

frontend:
  url: http://localhost:3000/

backend:
  url: http://localhost:8080/

website:
  domain: localhost


# Exclude SecurityAutoConfiguration to disable Spring Security auto-configuration
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.datasource.hikari.initializationFailTimeout: 60000

---
# for production
spring:
  config:
    activate:
      on-profile: prod
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://db-movingexpress-do-user-15580099-0.c.db.ondigitalocean.com:25060/movingexpress-db
    username: ${spring.mysql.username}
    password: ${spring.mysql.password}

  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: mysql
      mode: always
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  error:
    whitelabel:
      enabled: false
    include-binding-errors: always
    include-message: always
  port: 8080

frontend:
  url: https://movingexpress.systems/

backend:
  url: https://api.movingexpress.systems/

website:
  domain: movingexpress.systems

spring.datasource.hikari.initializationFailTimeout: 60000


